- name: Install git, ripgrep and fd from package
  package:
    name:
      - git
      - ripgrep
      - fd-find
    state: latest
  become: yes

- name: Install Rust / Cargo from official installer
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"

- name: Install exa
  shell: "{{ ansible_env.HOME }}/.cargo/bin/cargo install exa"

- name: Install bat
  shell: "{{ ansible_env.HOME }}/.cargo/bin/cargo install --locked bat"
    
- name: Install zoxide
  shell: "{{ ansible_env.HOME }}/.cargo/bin/cargo install --locked zoxide"

- name: Add zoxide init to zshrc
  lineinfile:
    path: "{{ zshrc_file }}"
    regexp: '^eval.*zoxide init zsh'
    line: eval "$(zoxide init zsh)"

