- name: Install required packages
  package:
    name:
      - git
      - curl
      - gzip
      - ripgrep
      - fzf
    state: latest
  become: yes

- name: Ensure ~/.local/bin directory exists
  file:
    path: "{{ local_bin_dir }}"
    state: directory
    recurse: yes
    mode: 0750

- name: Install lazygit from binary source
  shell: curl -L https://github.com/jesseduffield/lazygit/releases/download/v0.35/lazygit_0.35_Linux_x86_64.tar.gz | tar -z -C ~/.local/bin -x lazygit

- name: Install neovim from provided deb package
  apt:
    deb: https://github.com/neovim/neovim/releases/download/v0.7.2/nvim-linux64.deb
  become: true

- name: Ensure .config directory exists
  file:
    path: "{{ nvim_config_dir }}"
    state: directory
    recurse: yes
    mode: 0750

- name: Download Astrovim
  git:
    dest: "{{ nvim_config_dir }}"
    repo: https://github.com/AstroNvim/AstroNvim
    depth: 1
    clone: yes
    force: yes

- name: Ensure user config directory exists
  file:
    path: "{{ nvim_user_config_dir }}"
    state: directory
    recurse: yes
    mode: 0750

- name: Copy user init.lua
  copy:
    src: "{{ nvim_init_lua_src }}"
    dest: "{{ nvim_user_config_dir }}/init.lua"

- name: Ensure alias file exists
  file:
    path: "{{ zsh_alias_file }}"
    state: touch
    mode: 0750

- name: Ensure vim alias is set to nvim
  lineinfile:
    path: "{{ zsh_alias_file }}"
    regexp: '^alias vim='
    line: alias vim='nvim'

- name: Run PackerSync to update Astronvim plugins
  shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
