# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Path to Go
export PATH=$PATH:/usr/local/go/bin

ZSH_THEME="robbyrussell"

CASE_SENSITIVE="true"
HIST_STAMPS="yyyy-mm-dd"

bindkey '^ ' autosuggest-accept
plugins=(git docker-compose zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# Add specific local aliases here
if [ -f "$HOME/.zsh_aliases" ]; then
    source ~/.zsh_aliases
fi
