- name: Install Astrovim
  hosts: localhost
  vars:
    zsh_alias_file: "{{ ansible_env.HOME }}/.zsh_aliases"
    nvim_config_dir: "{{ ansible_env.HOME }}/.config/nvim"
    nvim_user_config_dir: "{{ nvim_config_dir }}/lua/user"
    nvim_init_lua_src: "config_files/nvim_init.lua"
    local_bin_dir: "{{ ansible_env.HOME }}/.local/bin"
  roles:
    - astronvim

